.TH "src Directory Reference" 3 "Version 0.1" "shmemvv" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBinclude\fP"
.br
.ti -1c
.RI "directory \fBtests\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBmain\&.cpp\fP"
.br
.RI "Driver file for the test suite\&. "
.ti -1c
.RI "file \fBroutines\&.cpp\fP"
.br
.RI "Contains function pointer declarations and routine loading function for the OpenSHMEM library\&. "
.in -1c
