.TH "src/tests/teams Directory Reference" 3 "Version 0.1" "shmemvv" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tests/teams Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBteams_tests\&.cpp\fP"
.br
.RI "Contains OpenSHMEM teams tests\&. "
.ti -1c
.RI "file \fBteams_tests\&.hpp\fP"
.br
.RI "Contains function declarations for the OpenSHMEM teams tests\&. "
.in -1c
