.TH "src/tests/collectives Directory Reference" 3 "Version 0.1" "shmemvv" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tests/collectives Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBcollectives_tests\&.cpp\fP"
.br
.RI "Contains tests for various OpenSHMEM collective routines\&. "
.ti -1c
.RI "file \fBcollectives_tests\&.hpp\fP"
.br
.RI "Contains function declarations for the OpenSHMEM collectives tests\&. "
.in -1c
