.TH "src/tests/locking Directory Reference" 3 "Version 0.1" "shmemvv" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tests/locking Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBlocking_tests\&.cpp\fP"
.br
.RI "Contains OpenSHMEM distributed locking tests\&. "
.ti -1c
.RI "file \fBlocking_tests\&.hpp\fP"
.br
.RI "Contains function declarations for the OpenSHMEM distributed locking tests\&. "
.in -1c
