.TH "src/include Directory Reference" 3 "Version 0.1" "shmemvv" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/include Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBroutines\&.hpp\fP"
.br
.RI "Contains routine pointers to avoid compiler errors if a routine is not implemented\&. "
.ti -1c
.RI "file \fBshmemvv\&.hpp\fP"
.br
.RI "Contains helper function declarations for the OpenSHMEM verification/validation test suite\&. "
.in -1c
