.TH "src/tests/remote Directory Reference" 3 "Version 0.1" "shmemvv" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tests/remote Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBremote_tests\&.cpp\fP"
.br
.RI "Contains OpenSHMEM remote memory access tests\&. "
.ti -1c
.RI "file \fBremote_tests\&.hpp\fP"
.br
.RI "Contains function declarations for the OpenSHMEM remote memory access tests\&. "
.in -1c
