.TH "src/tests/atomics Directory Reference" 3 "Version 0.1" "shmemvv" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/tests/atomics Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBatomics_tests\&.cpp\fP"
.br
.RI "Contains tests for OpenSHMEM atomic routines\&. "
.ti -1c
.RI "file \fBatomics_tests\&.hpp\fP"
.br
.RI "Contains function declarations for the OpenSHMEM atomic memory operations tests\&. "
.in -1c
