.TH "test_options" 3 "Version 0.1" "shmemvv" \" -*- nroff -*-
.ad l
.nh
.SH NAME
test_options \- Struct to hold selected tests options\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <shmemvv\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtest_options\fP ()"
.br
.RI "Constructor to initialize all flags to false\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBtest_all\fP"
.br
.ti -1c
.RI "bool \fBtest_setup\fP"
.br
.ti -1c
.RI "bool \fBtest_threads\fP"
.br
.ti -1c
.RI "bool \fBtest_mem\fP"
.br
.ti -1c
.RI "bool \fBtest_teams\fP"
.br
.ti -1c
.RI "bool \fBtest_ctx\fP"
.br
.ti -1c
.RI "bool \fBtest_remote\fP"
.br
.ti -1c
.RI "bool \fBtest_atomics\fP"
.br
.ti -1c
.RI "bool \fBtest_signaling\fP"
.br
.ti -1c
.RI "bool \fBtest_collectives\fP"
.br
.ti -1c
.RI "bool \fBtest_pt2pt_synch\fP"
.br
.ti -1c
.RI "bool \fBtest_mem_ordering\fP"
.br
.ti -1c
.RI "bool \fBtest_locking\fP"
.br
.ti -1c
.RI "bool \fBhelp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Struct to hold selected tests options\&. 
.PP
Definition at line \fB44\fP of file \fBshmemvv\&.hpp\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "test_options::test_options ()\fR [inline]\fP"

.PP
Constructor to initialize all flags to false\&. 
.PP
Definition at line \fB63\fP of file \fBshmemvv\&.hpp\fP\&.
.nf
63                  :
64     test_all(false), test_setup(false), test_threads(false),
65     test_mem(false), test_teams(false), test_ctx(false),
66     test_remote(false), test_atomics(false), test_signaling(false),
67     test_collectives(false), test_pt2pt_synch(false),
68     test_mem_ordering(false), test_locking(false), help(false) {}
.PP
.fi

.SH "Member Data Documentation"
.PP 
.SS "bool test_options::help"
Flag to display help message 
.PP
Definition at line \fB58\fP of file \fBshmemvv\&.hpp\fP\&.
.SS "bool test_options::test_all"
Flag to run all tests 
.PP
Definition at line \fB45\fP of file \fBshmemvv\&.hpp\fP\&.
.SS "bool test_options::test_atomics"
Flag to run atomic memory operations tests 
.PP
Definition at line \fB52\fP of file \fBshmemvv\&.hpp\fP\&.
.SS "bool test_options::test_collectives"
Flag to run collective operations tests 
.PP
Definition at line \fB54\fP of file \fBshmemvv\&.hpp\fP\&.
.SS "bool test_options::test_ctx"
Flag to run communication management tests 
.PP
Definition at line \fB50\fP of file \fBshmemvv\&.hpp\fP\&.
.SS "bool test_options::test_locking"
Flag to run distributed locking tests 
.PP
Definition at line \fB57\fP of file \fBshmemvv\&.hpp\fP\&.
.SS "bool test_options::test_mem"
Flag to run memory management tests 
.PP
Definition at line \fB48\fP of file \fBshmemvv\&.hpp\fP\&.
.SS "bool test_options::test_mem_ordering"
Flag to run memory ordering tests 
.PP
Definition at line \fB56\fP of file \fBshmemvv\&.hpp\fP\&.
.SS "bool test_options::test_pt2pt_synch"
Flag to run point-to-point synchronization tests 
.PP
Definition at line \fB55\fP of file \fBshmemvv\&.hpp\fP\&.
.SS "bool test_options::test_remote"
Flag to run remote memory access tests 
.PP
Definition at line \fB51\fP of file \fBshmemvv\&.hpp\fP\&.
.SS "bool test_options::test_setup"
Flag to run setup tests 
.PP
Definition at line \fB46\fP of file \fBshmemvv\&.hpp\fP\&.
.SS "bool test_options::test_signaling"
Flag to run signaling operations tests 
.PP
Definition at line \fB53\fP of file \fBshmemvv\&.hpp\fP\&.
.SS "bool test_options::test_teams"
Flag to run team management tests 
.PP
Definition at line \fB49\fP of file \fBshmemvv\&.hpp\fP\&.
.SS "bool test_options::test_threads"
Flag to run thread support tests 
.PP
Definition at line \fB47\fP of file \fBshmemvv\&.hpp\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for shmemvv from the source code\&.
